### PR TITLE
RxSwift 2

### PR DESCRIPTION
**Pull request by esttorhe**
This brings support for `RxSwift` 2.0

### CODE REVIEW

**Comment by esttorhe** [comment]
would love if some @RxSwiftCommunity/contributors would give this the thumbs up; if no one feels comfortable enough i'd merge and release a new version tomorrow though.

**Comment by thanegill** [comment]
Is it best practice to commit the Pods directory? (I'm genuinely asking. I personally don't but it could be the thing to do.)

**Comment by esttorhe** [comment]
The Pods directory is added to the repo so that `Carthage` can be supported.

The way it works is via a «phantom» project with the correctly shared Schemes making this project work with `Carthage` «out of the box»

**Comment by kzaher** [comment]
Hi @esttorhe ,

I also have issues with supporting multiple package managers in https://github.com/RxSwiftCommunity/RxDataSources.

¯\\\_(ツ)\_/¯ 

The best plan I've got is explained here https://github.com/RxSwiftCommunity/RxDataSources/pull/1.

I've taken a look at Moya and I believe this should be working, right?

Hoping in this way we wouldn't need to commit any RxSwift code.

**Comment by esttorhe** [comment]
@kzaher that's interesting; my first approach to supporting `Carthage` was off on `Moya`'s implementation at the time; didn't know they changed the approach.

I'll take a look at it and fix it accordingly although i think i would do that on another `PR`. 
Would rather have `3.0.0` out supporting `RxSwift` 2 now so people that are using it can build with latest and released version of everything; then fix that `Carthage` support.

**Comment by ashfurrow** [comment]
Just curious – has anyone asked for Carthage support on RxViewModel?

**Comment by esttorhe** [comment]
Well; `RxViewModel` has supported `Carthage` since its conception
¯\\\_(ツ)\_/¯ 

Not supporting it now could be «bad» if there's a chance that 1 or 2 users are depending on it (even though I doubt it)

**Comment by ashfurrow** [comment]
Ah, gotcha. I don't add support for Carthage until someone asks :stuck_out_tongue: Even then, I don't really _add_ it so much as I accept pull requests that do it for me.

**Comment by esttorhe** [comment]
Hahahaha; yeah i've noticed.

I'm not too well versed in `Carthage` myself and that's why `CocoaPods` template was a blessing.

I'll take a look at the current/new approach.

Unless this is a real blocker I would really appreciate the merge :blush: 
The project I'm working on for my day job uses `RxViewModel` and `RxSwift` and we are trying to update to official 2.0 version

**Comment by ashfurrow** [comment]
Cool cool – the diff is hard to read, but it all looks good 👍 

The CI is red, but the error message look related to install code coverage tools? I'll merge now and we can fix afterward.

**Comment by esttorhe** [comment]
Thanks Ash. I'll make a new pod release now :bow:

**Pull request merged**
