### PR TITLE
Update to Swift 3 / RxSwift 3

### PR DESCRIPTION
**Pull request by gregpardo**
Probably shouldn't release this until RxSwift comes out of 3.0.0-beta.X.

Bumped version to 4.0 for major Swift 3 change.

### CODE REVIEW

**Comment by davidlondono** [comment]
change travis yml to xcode8

**Comment by esttorhe** [comment]
Hi @gregpardo and @davidlondono sorry for being away.

Just recently relocated to 🇩🇪 and I've been going crazy with the move and getting all the paperwork.

Haven't had the time to check locally but it looks like its failing due to some `Danger` issues.


If any of you can vouch for the commit I would say go ahead and merge this.

**Comment by nechris** [comment]
Hi @gregpardo and @davidlondono  ...seemingly var disposeKey: Bag<Disposable>.KeyType? doesn't work anymore as Bag and KeyType seem to be private in RxSwift 3.0 now. When explicitly setting the Bag struct and KeyType type alias in RxSwift to public, it works. But I guess this would have to be changed on Rx-side then.
Any thoughts/ideas on this?

**Comment by gregpardo** [comment]
@nechris I've updated the branch with RxSwift 3.0 compatibility. This was the final thing we were waiting for. Not sure how to get these merged in with the current read only access to CI though.

**Comment by beretis** [comment]
Guys, when this will be merged? thank you

**Comment by esttorhe** [comment]
Fixed with #45

**Pull request closed without merging**
