### PR TITLE
Fix retain cycle

### PR DESCRIPTION
**Pull request by sprynmr**
Noticed a retain cycle when using RxViewModel.

### CODE REVIEW

**Comment by sprynmr** [comment]
Actually, still seeing the issue (though I'm pretty sure the change I made in this PR should still eliminate one retain cycle.)

Documenting the issue here: https://github.com/RxSwiftCommunity/RxViewModel/issues/31

**Comment by esttorhe** [comment]
😱 good catch @sprynmr 

`CirceCI` has been off for quite some time (need to fix this).

I'll go ahead and merge this (giving that its true that this should take at least 1 retain cycle)


Thanks for the `PR`.


BTW. I'm following Ash Furrow's idea and I'm offering access to the repo, etc to anyone that submits a `PR` and gets merged; let me know if that's something you would be interested in 😄

**Comment by sprynmr** [comment]
Hey sure. At some point I think it would make sense to move to a protocol first approach for this, similar to the open PR https://github.com/RxSwiftCommunity/RxViewModel/pull/25. Not sure exactly what that would look like (maybe that PR is dead on), but something I was going to look at at some point here.

**Comment by esttorhe** [comment]
Yes; definitely the protocol approach was always on my mind but at the time of the creation of this library i lacked enough knowledge to make it happen as I wanted it to be.

I need to check #25 deeply because it could be the solution or might too close to only need very few tweaks 😄 

I'll send you an invite to the org right now BTW

**Pull request merged**
