### PR TITLE
Converted to swift 4 and rxswift 4

### LINKED ISSUE #58: Update with RXSwift 4
Currently can't use it with RxSwift 4

### PR DESCRIPTION
**Pull request by AYastrebov**
Fixes #58

### CODE REVIEW

**Comment by freak4pc** [comment]
I'm not sure there's a need for a 6.0 for this version... I think it can be a minor patch and not necessarily major

**Comment by AYastrebov** [comment]
@freak4pc 5.1.0 would be ok?

**Comment by AYastrebov** [comment]
@esttorhe yes, I'd love to be a part of organisation, thanks!

**Comment by esttorhe** [comment]
@AYastrebov I'm going to close this `PR` in favor of #60 

Feel free to follow and comment on it; I'll send the invite in a few.

Thanks

**Pull request closed without merging**
